name: check-licenses

on:
  workflow_dispatch:
  schedule:
  - cron: 0 0 1 * *

jobs:
  license_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: pilosus/action-pip-license-checker@v0.5.0
      id: license_check_report
      with:
        requirements: requirements.txt
        fail: StrongCopyleft,NetworkCopyleft,Other,Error
        exclude: ^(pylint|coreutils).*
        with-totals: true
        table-headers: true
    - name: Print report
      if: ${{ always() }}
      run: echo "${{ steps.license_check_report.outputs.report }}"
