name: pre-commit

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
          ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}
    - uses: actions/setup-python@v2
    - run: export MYPYPATH=`pwd`:$MYPYPATH
    - run: pip install poetry
    - uses: pre-commit/action@v2.0.0
