name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: export MYPYPATH=`pwd`:$MYPYPATH
    - run: pip install poetry
    - uses: pre-commit/action@v2.0.3

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: pip install -r requirements.txt
    - run: python3 -m doctest -v **/*.py
    - run: python3 -m unittest -v
